name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: action/checkout@v2
    
    - name: Rub a one-line script
      run: echo Hello, world!
    
    - name: Run a multi-scipt
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
